name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}  # Ensure this is "ubuntu"
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/fastapi-app
            git pull origin main
            docker-compose down
            docker-compose up -d --build

           
